name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  spotless:
    runs-on: ubuntu-latest
    name: Check eclipse formatting rules

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run spotless checks
      run: mvn --batch-mode
               --also-make
               --no-transfer-progress
               --projects api
               --define maven.javadoc.skip=true
               --define skipTests=true
               --define spotless.check.skip=false
               verify

